name: Update Trending Repositories

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Checkout repository
        uses: actions/checkout@v2  # Ensure the repository is checked out

      - name: Run script to update trending repositories
        run: python ./.github/scripts/trending_repos.py  # Adjust path to the script

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add trending_repos.md
          git commit -m "Update trending repositories"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
